### ISSUE TITLE
Canonicalization is disabled by default

### ISSUE THREAD

**Issue by k3yavi** [10XGenomics/rust-pseudoaligner#3]
Hi guys,

I think we've disabled the canonicalization by default [here](https://github.com/10XGenomics/rust-pseudoaligner/blob/master/src/build_index.rs#L103). We should parobably parametrize it or as mentioned in https://github.com/10XGenomics/rust-debruijn/issues/10 set it to always true ?

**Comment by pmarks** [comment]
Thanks @k3yavi  -- we definitely don't want to canonicalize when we using this with stranded assays (all the 10x RNA-seq assays are stranded), because we want to be able to report whether the read was sense or anti-sense, so I think we have the right default for our use case.  This will require the user to re-query the index with the RC of the read to get an anti-sense alignment.  

I'm open to adding optional support for non-stranded reads, if you want to make a PR, but it's probably not a priority for us.

**Comment by k3yavi** [comment]
Makes sense. I think I did customized it at some point of time but currently lost track with other things. I'll make a PR, with an optional parameter, once I get back to the project. Thanks for the clarification.
